name: Go

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
